### ISSUE TITLE
surf serial communication garble

### ISSUE THREAD

**Issue by tim-bormann** [tp-freeforall/prod#24]
Hello,
the TestSerial app and every other serial communication running on my surf boards (Rev.B2) only produces garble bytes:
00000000: ff ef f7 6f ff ef f7 6f   ff ef f7 6f ff ef f7 ef 
00000010: ff ef f7 ef ff ef f7 ef   ff ff ef f7 ef ff ef f7 
00000020: ef
(These are 8 serial AM packets from TestSerial received with 115200 baud, note how they are way too short)

RadioCountToLeds works fine, and with the old osian branch my surf boards produce correct output. So suppose its not a hardware or cable fault, but something with the current tinyprod code.
I am using the tinyprod toolchain.

Regards, Tim

**Comment by cire831** [comment]
The most likely cause is baud rate changes.  I'm pretty sure I changed
things up but don't remember what I did.

surf isn't supported any more and is an orphaned board.   I also no longer
have the osian surf source code around and it would take a bunch of work on
my part to resurrect it.   Not going to happen.

Do you have a jtag debugger?

What I would do is fire up the jtag debugger.   First I would use the Osian
code and then take a look at the settings of what every USCI you are using
to talk in UART mode.

Then I would fire up the tinyprod code and look at the same settings.

The configuration also depends on how the clocks are set up.

eric

On Fri, Jun 21, 2013 at 5:50 AM, tim-bormann notifications@github.comwrote:

> Hello,
> the TestSerial app and every other serial communication running on my surf
> boards (Rev.B2) only produces garble bytes:
> 00000000: ff ef f7 6f ff ef f7 6f ff ef f7 6f ff ef f7 ef
> 00000010: ff ef f7 ef ff ef f7 ef ff ff ef f7 ef ff ef f7
> 00000020: ef
> (These are 8 serial AM packets from TestSerial received with 115200 baud,
> note how they are way too short)
> 
> RadioCountToLeds works fine, and with the old osian branch my surf boards
> produce correct output. So suppose its not a hardware or cable fault, but
> something with the current tinyprod code.
> I am using the tinyprod toolchain.
> 
> Regards, Tim
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tp-freeforall/prod/issues/24
> .

## 

Eric B. Decker
Senior (over 50 :-) Researcher
