### ISSUE TITLE
[MSP430] Can't use USCI A as SPI master

### ISSUE THREAD

**Issue by tgtakaoka** [tp-freeforall/prod#28]
Unfortunately current implementation of [`Msp430SpiNoDmaP.nc`](https://github.com/tp-freeforall/prod/blob/64a2e748ba69ca2970f466f13c7b3e731d7bc240/tos/chips/msp430/x2xxx/usci/Msp430SpiDmaP.nc#L65) uses `HplMsp430UsciB` as USCI interface, and it works only for USCI B. If we choose USCI A as SPI channel, it ends up an error since it is incompatible with [`Msp430SpiA0NoDmaP.nc`](https://github.com/tp-freeforall/prod/blob/64a2e748ba69ca2970f466f13c7b3e731d7bc240/tos/chips/msp430/x2xxx/usci/Msp430SpiA0NoDmaP.nc#L68).

To solve this, we may want to refactor `Msp430UsciA` and `Msp430UsciB` interfaces into four, lets say, `Msp430Usci`, `Msp430UsciSpi`, `Msp430UsciUart`, and `Msp430UsciI2C`.

WDYT?

**Comment by cire831** [comment]
fixed by 5f9b2bf27b0e1c4ecd5a0845a7731eef640947aa
